apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault
  name: vault
  namespace: argo
spec:
  ports:
  - name: "8222"
    port: 8222
    protocol: TCP
  type: ClusterIP
  clusterIP: "None"
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vault
  namespace: argo
subsets:
  - addresses:
      - ip: 172.17.0.1
    ports:
      - port: 8222
