apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: webapp-color
spec:
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 10 }
        - setWeight: 60
        - pause: { }
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: kodekloud/webapp-color
          imagePullPolicy: IfNotPresent
          name: webapp
          ports: 
            - containerPort: 8080
              protocol: TCP
