resources:
  - ./../../base
images:
  - name: kodekloud/webapp-color
    newTag: v2
commonLabels:
  app: webapp-prd

patches:
  - patch: |-
      apiVersion: argoproj.io/v1alpha1
      kind: Rollout
      metadata:
        name: webapp-color
      spec:
        replicas: 5
